### ISSUE TITLE
Build error on Mac OS 10.9.5

### ISSUE THREAD

**Issue by caozigao** [UCLA-Plasma-Simulation-Group/JupyterPIC#2]
I receive the following error message when I run "docker build -t osiris-class -f Dockerfile-local .":

filesystem layer verification failed for digest sha256:074b7bf56d532b9ed9b610cf8d28e447156552cbdedeccb79df0caa879e8b5d2

I am using Mac OS 10.9.5?

**Comment by benjum** [comment]
Resolved offline.
